### PR TITLE
Added fit_transform method to DataFrameMapper

### PR DESCRIPTION
**Pull request by SandroCasagrande**
Attempt to solve #150 by implementing the method fit_transform for DataFrameMapper.

My implementation follows the typical approach (e.g. in sklearn's DictVectorizer) of using a private _transform( ... , do_fit) method which optionally allows for fitting. Most of the changes are therefore due to some small refactoring. 3 new test are included, and a 3 existing tests with mock objects had to be adapted but are semantically unchanged.

### CODE REVIEW

**Comment by FlorisHoogenboom** [comment]
Does anyone have an idea why the AttributeError `AttributeError: module 'pandas.core.common' has no attribute 'array_equivalent'` is raised here? It seems that array_equivalent has been deprecated from pandas.core (which is a private module without any API stability guarantees). I'm curious why this error only appears in this PR. For the rest it seems all checks pass.

**Comment by dukebody** [comment]
@FlorisHoogenboom yes sorry, it's an issue with newer Pandas version that were incorrectly picked up by the CI system. If you rebase with master these failures will go away.

**Comment by SandroCasagrande** [comment]
Great! Pleased that you are interested in having this.

**Comment by dukebody** [comment]
Looking good! I'm going to merge it and it will make it to the new release.

**Comment by dukebody** [comment]
Superseded by #169, which is a copy of this PR but rebased on master. Thanks a lot @SandroCasagrande !

**Pull request closed without merging**
