### PR TITLE
DOC: add pypi and conda-forge badges

### PR DESCRIPTION
**Pull request by raybellwaves**

### CODE REVIEW

**Comment by ragrawal** [comment]
Hi @raybellwaves , how new version of sklearn-pandas will get updated on condo-forge ?

**Comment by raybellwaves** [comment]
bot if no change to dependencies. Note: you can make a PR to https://github.com/conda-forge/sklearn-pandas-feedstock/blob/master/recipe/meta.yaml#L45 to add your self as a maintainer. Don't forget to bump the build version.

**Comment by ragrawal** [comment]
if you don't mind, can you help create a GitHub action to upload sklearn-pandas to conda within this package itself. This will help create everything in place rather than spreading it over multiple packages.

**Comment by raybellwaves** [comment]
The way conda-forge works is you release on pypi then a bot updates it in the feedstock

**Comment by ragrawal** [comment]
@raybellwaves how familiar are you with github actions. If possible, I would like to create a workflow that can do the following things:
1. create a release 
2. upload the package on pypi 
3. upload the package on conda.

**Comment by ragrawal** [comment]
@raybellwaves I finally got time to read about Conda-forge-feedstock. I released v2.1.0 for sklearn_pandas and spicy dependency has changed. I tried creating a branch on sklearn-pandas-feedstock but not able to push to it as I don't have permission. Is it something you can provide ?

**Review by ragrawal — APPROVED** [review]

**Comment by raybellwaves** [comment]
I don't maintain that repo: https://github.com/conda-forge/sklearn-pandas-feedstock/blob/master/recipe/meta.yaml#L45

**Pull request merged**
